import { useEffect, useState } from 'react';
import { NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import { Activity, Copy, CreditCard, KeyRound, Landmark, LogOut, Settings, Smartphone, WalletCards } from 'lucide-react';
import api from '../../api';
import TransactionDetail from '../TransactionDetail';
import ProfileView from './ProfileView';
import '../../App.css';

const paymentMethods = [
  { id: 'card', label: 'Cards', description: 'Paystack-style test card form', icon: CreditCard },
  { id: 'bank_transfer', label: 'Bank transfer', description: 'Mock account for the payment currency', icon: Landmark },
  { id: 'bank_app', label: 'Bank app', description: 'Simulated local banking approval', icon: Smartphone },
  { id: 'crypto', label: 'Crypto address', description: 'Mock address for the selected asset', icon: WalletCards },
];

function Overview({ profile }) {
  const [transactions, setTransactions] = useState([]);
  const [selectedTransaction, setSelectedTransaction] = useState(null);
  const [form, setForm] = useState({ fiat_amount: 100 });
  const [link, setLink] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { api.get('/checkout/history').then(response => setTransactions(response.data.data)).catch(() => setError('Ledger unavailable.')); }, []);
  async function createSession(event) { event.preventDefault(); setError(''); try { const { data } = await api.post('/checkout/session', form); setLink(`${window.location.origin}${data.checkout_url}`); } catch (err) { setError(err.response?.data?.detail || 'Could not create session.'); } }
  const copyValue = value => navigator.clipboard.writeText(value);
  if (selectedTransaction) return <TransactionDetail transaction={selectedTransaction} onClose={() => setSelectedTransaction(null)} />;
  return <>
    <div className="page-heading"><div><p className="eyebrow">OVERVIEW</p><h1>Payment operations</h1><p className="muted">A live view of your settlement activity.</p></div><span className="status-dot">Prototype systems nominal</span></div>
    <div className="stat-grid"><div className="stat-card"><Activity size={18}/><span>Ledger entries</span><strong>{transactions.length}</strong></div><div className="stat-card"><WalletCards size={18}/><span>Default settlement</span><strong>{profile.settlement_asset || 'NGN'}</strong></div><div className="stat-card"><CreditCard size={18}/><span>Checkout methods</span><strong>{profile.payment_options?.length || 0}</strong></div></div>
    <section className="content-grid"><div className="surface"><div className="surface-title"><div><p className="eyebrow">QUICK ACTION</p><h2>Create checkout session</h2><p className="muted">Customer-facing price is entered in NGN. Settlement uses your saved {profile.settlement_asset} setting.</p></div></div><form onSubmit={createSession} className="inline-form"><label>Amount (NGN)<input type="number" min="1" step="0.01" value={form.fiat_amount} onChange={event => setForm({ fiat_amount: Number(event.target.value) })}/></label><button className="primary-button">Generate link</button></form>{link && <div className="generated-link"><a href={link} title="Open checkout link">{link}</a><button className="icon-button" title="Copy checkout link" onClick={() => copyValue(link)}><Copy size={16}/></button></div>}{error && <p className="form-error">{error}</p>}</div></section>
    <section className="content-grid"><div className="surface"><div className="surface-title"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Immutable ledger</h2></div></div>{transactions.length ? <div className="ledger-list">{transactions.slice(0, 5).map(tx => <div className="ledger-row ledger-row-detail clickable-row" key={tx.tx_id} onClick={() => setSelectedTransaction(tx)} role="button" tabIndex="0" onKeyDown={event => event.key === 'Enter' && setSelectedTransaction(tx)}><span className="ledger-mark">✓</span><div><strong>{tx.currency}</strong><small>{new Date(tx.created_at).toLocaleString()}</small><span className="data-tag">ID <code>{tx.tx_id}</code></span><span className="data-tag">HASH <code>{tx.current_hash}</code></span></div><span className="status-tag">{tx.status || 'completed'}</span><b>{Number(tx.settlement_value).toLocaleString()}</b><button className="icon-button" title="Copy transaction ID" onClick={event => { event.stopPropagation(); copyValue(tx.tx_id); }}><Copy size={15}/></button><button className="icon-button" title="Copy SHA-256 hash" onClick={event => { event.stopPropagation(); copyValue(tx.current_hash); }}><Copy size={15}/></button></div>)}</div> : <p className="muted empty-state">No completed transactions yet.</p>}</div></section>
  </>;
}

function SettingsView({ profile, setProfile }) {
  const [asset, setAsset] = useState(profile.settlement_asset); const [url, setUrl] = useState(profile.webhook_url || ''); const [options, setOptions] = useState(profile.payment_options || paymentMethods.map(method => method.id)); const [saved, setSaved] = useState(false);
  function toggle(id) { setOptions(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]); }
  async function save(event) { event.preventDefault(); await api.patch('/auth/settings', { settlement_asset: asset, webhook_url: url || null, payment_options: options }); setProfile({ ...profile, settlement_asset: asset, webhook_url: url, payment_options: options }); setSaved(true); }
  return <section className="surface narrow"><p className="eyebrow">CONFIGURATION</p><h1>Checkout & settlement</h1><p className="muted">Choose the settlement rail and which simulated payment methods customers can see.</p><form onSubmit={save} className="stack-form"><label>Default settlement asset<select value={asset} onChange={event => setAsset(event.target.value)}><option>NGN</option><option>USD</option><option>GBP</option><option>EUR</option><option>BTC</option><option>USDT</option></select></label><div><p className="field-heading">Visible checkout methods</p><div className="option-list">{paymentMethods.map(method => { const Icon = method.icon; return <label className="option-row" key={method.id}><input type="checkbox" checked={options.includes(method.id)} onChange={() => toggle(method.id)}/><Icon size={17}/><span><strong>{method.label}</strong><small>{method.description}</small></span></label>; })}</div></div><label>Webhook endpoint<input type="url" placeholder="https://merchant.example/hooks/verve" value={url} onChange={event => setUrl(event.target.value)}/></label><button className="primary-button" disabled={!options.length}>Save settings</button>{saved && <p className="success-text">Checkout preferences saved.</p>}</form></section>;
}
function WithdrawView({ profile }) { const [amount, setAmount] = useState(''); const [destination, setDestination] = useState(''); const [message, setMessage] = useState(''); async function submit(event) { event.preventDefault(); try { const { data } = await api.post('/checkout/withdrawals', { amount: Number(amount), destination }); setMessage(`${data.amount} ${data.asset} mock withdrawal queued.`); setAmount(''); setDestination(''); } catch (err) { setMessage(err.response?.data?.detail || 'Withdrawal could not be queued.'); } } return <section className="surface narrow"><p className="eyebrow">MOCK TREASURY</p><h1>Withdraw funds</h1><p className="muted">Request a simulated payout in your configured settlement asset: <strong>{profile.settlement_asset}</strong>.</p><form onSubmit={submit} className="stack-form"><label>Amount ({profile.settlement_asset})<input type="number" min="0.01" step="0.01" required value={amount} onChange={event => setAmount(event.target.value)}/></label><label>Destination<input required placeholder="demo-destination-001" value={destination} onChange={event => setDestination(event.target.value)}/></label><button className="primary-button">Queue mock withdrawal</button>{message && <p className="success-text">{message}</p>}</form></section>; }
function Integration({ profile }) { return <section className="surface narrow"><p className="eyebrow">DEVELOPER ACCESS</p><h1>API & integration</h1><p className="muted">Use this key from your server only. This prototype accepts test requests only.</p><div className="secret-field"><KeyRound size={17}/><code>{profile.api_key}</code></div><pre>{`const session = await fetch('/api/checkout/session', {\n  method: 'POST',\n  headers: { Authorization: 'Bearer YOUR_JWT' },\n  body: JSON.stringify({ fiat_amount: 125 })\n});`}</pre></section>; }
export default function DashboardLayout() { const navigate = useNavigate(); const [profile, setProfile] = useState(null); useEffect(() => { api.get('/auth/me').then(response => setProfile(response.data)).catch(() => { localStorage.removeItem('vg_access_token'); navigate('/login'); }); }, [navigate]); if (!profile) return <main className="loading-screen">Loading control room...</main>; return <div className="dashboard-shell"><aside className="sidebar"><div className="brand"><span>VG</span><strong>Verve Gate</strong></div><p className="sidebar-label">MERCHANT CONSOLE</p><nav><NavLink to="/dashboard" end><Activity size={17}/>Overview</NavLink><NavLink to="/dashboard/profile"><Users size={17}/>Profile</NavLink><NavLink to="/dashboard/integration"><KeyRound size={17}/>API & Integration</NavLink><NavLink to="/dashboard/settings"><Settings size={17}/>Checkout settings</NavLink><NavLink to="/dashboard/withdraw"><WalletCards size={17}/>Withdraw</NavLink></nav><button className="logout-button" onClick={() => { localStorage.removeItem('vg_access_token'); navigate('/login'); }}><LogOut size={17}/>Sign out</button></aside><main className="dashboard-main"><Routes><Route index element={<Overview profile={profile}/>} /><Route path="profile" element={<ProfileView profile={profile}/>} /><Route path="integration" element={<Integration profile={profile}/>} /><Route path="settings" element={<SettingsView profile={profile} setProfile={setProfile}/>} /><Route path="withdraw" element={<WithdrawView profile={profile}/>} /></Routes></main></div>; }
