import { useEffect, useState } from 'react';
import { NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import { Activity, Copy, CreditCard, KeyRound, LogOut, Settings, WalletCards } from 'lucide-react';
import api from '../../api';
import '../../App.css';

function Overview({ profile }) {
  const [transactions, setTransactions] = useState([]); const [form, setForm] = useState({ fiat_amount: 100, fiat_currency: 'USD', settlement_asset: profile?.settlement_asset || 'NGN' }); const [link, setLink] = useState(''); const [error, setError] = useState('');
  useEffect(() => { api.get('/checkout/history').then(r => setTransactions(r.data.data)).catch(() => setError('Ledger unavailable.')); }, []);
  async function createSession(e) { e.preventDefault(); setError(''); try { const { data } = await api.post('/checkout/session', form); setLink(`${window.location.origin}${data.checkout_url}`); } catch (err) { setError(err.response?.data?.detail || 'Could not create session.'); } }
  return <><div className="page-heading"><div><p className="eyebrow">OVERVIEW</p><h1>Payment operations</h1><p className="muted">A live view of your settlement activity.</p></div><span className="status-dot">Systems nominal</span></div><div className="stat-grid"><div className="stat-card"><Activity size={18}/><span>Ledger entries</span><strong>{transactions.length}</strong></div><div className="stat-card"><WalletCards size={18}/><span>Default settlement</span><strong>{profile?.settlement_asset || 'NGN'}</strong></div><div className="stat-card"><CreditCard size={18}/><span>Session horizon</span><strong>15 min</strong></div></div><section className="content-grid"><div className="surface"><div className="surface-title"><div><p className="eyebrow">QUICK ACTION</p><h2>Create checkout session</h2></div></div><form onSubmit={createSession} className="inline-form"><label>Amount<input type="number" min="1" step="0.01" value={form.fiat_amount} onChange={e => setForm({ ...form, fiat_amount: Number(e.target.value) })}/></label><label>Pay currency<select value={form.fiat_currency} onChange={e => setForm({ ...form, fiat_currency: e.target.value })}><option>USD</option><option>GBP</option><option>EUR</option><option>NGN</option></select></label><label>Settle in<select value={form.settlement_asset} onChange={e => setForm({ ...form, settlement_asset: e.target.value })}><option>NGN</option><option>USD</option><option>GBP</option><option>EUR</option><option>BTC</option><option>USDT</option></select></label><button className="primary-button">Generate link</button></form>{link && <div className="generated-link"><span>{link}</span><button className="icon-button" title="Copy checkout link" onClick={() => navigator.clipboard.writeText(link)}><Copy size={16}/></button></div>}{error && <p className="form-error">{error}</p>}</div><div className="surface"><div className="surface-title"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Immutable ledger</h2></div></div>{transactions.length ? <div className="ledger-list">{transactions.slice(0, 5).map(tx => <div className="ledger-row" key={tx.tx_id}><span className="ledger-mark">✓</span><div><strong>{tx.currency}</strong><small>{new Date(tx.created_at).toLocaleString()}</small></div><b>{Number(tx.settlement_value).toLocaleString()}</b></div>)}</div> : <p className="muted empty-state">No completed transactions yet.</p>}</div></section></>;
}

function SettingsView({ profile, setProfile }) { const [asset, setAsset] = useState(profile.settlement_asset); const [url, setUrl] = useState(profile.webhook_url || ''); const [saved, setSaved] = useState(false); async function save(e) { e.preventDefault(); await api.patch('/auth/settings', { settlement_asset: asset, webhook_url: url || null }); setProfile({ ...profile, settlement_asset: asset, webhook_url: url }); setSaved(true); } return <section className="surface narrow"><p className="eyebrow">CONFIGURATION</p><h1>Settlement settings</h1><p className="muted">Choose where Verve Gate resolves merchant funds and where signed events are delivered.</p><form onSubmit={save} className="stack-form"><label>Default settlement asset<select value={asset} onChange={e => setAsset(e.target.value)}><option>NGN</option><option>USD</option><option>GBP</option><option>EUR</option><option>BTC</option><option>USDT</option></select></label><label>Webhook endpoint<input type="url" placeholder="https://merchant.example/hooks/verve" value={url} onChange={e => setUrl(e.target.value)}/></label><button className="primary-button">Save settings</button>{saved && <p className="success-text">Settings saved.</p>}</form></section>; }
function Integration({ profile }) { return <section className="surface narrow"><p className="eyebrow">DEVELOPER ACCESS</p><h1>API & integration</h1><p className="muted">Use this key from your server only. Never expose it in browser code.</p><div className="secret-field"><KeyRound size={17}/><code>{profile.api_key}</code></div><pre>{`const session = await fetch('http://localhost:8000/api/checkout/session', {\n  method: 'POST',\n  headers: { Authorization: 'Bearer YOUR_JWT' },\n  body: JSON.stringify({\n    fiat_amount: 125, fiat_currency: 'USD', settlement_asset: 'NGN'\n  })\n});`}</pre></section>; }
export default function DashboardLayout() { const navigate = useNavigate(); const [profile, setProfile] = useState(null); useEffect(() => { api.get('/auth/me').then(r => setProfile(r.data)).catch(() => { localStorage.removeItem('vg_access_token'); navigate('/login'); }); }, [navigate]); if (!profile) return <main className="loading-screen">Loading control room...</main>; return <div className="dashboard-shell"><aside className="sidebar"><div className="brand"><span>VG</span><strong>Verve Gate</strong></div><p className="sidebar-label">MERCHANT CONSOLE</p><nav><NavLink to="/dashboard" end><Activity size={17}/>Overview</NavLink><NavLink to="/dashboard/integration"><KeyRound size={17}/>API & Integration</NavLink><NavLink to="/dashboard/settings"><Settings size={17}/>Settlement</NavLink></nav><button className="logout-button" onClick={() => { localStorage.removeItem('vg_access_token'); navigate('/login'); }}><LogOut size={17}/>Sign out</button></aside><main className="dashboard-main"><Routes><Route index element={<Overview profile={profile}/>} /><Route path="integration" element={<Integration profile={profile}/>} /><Route path="settings" element={<SettingsView profile={profile} setProfile={setProfile}/>} /></Routes></main></div>; }
